### ISSUE TITLE
Big Forge Update has broken Civitai Helper downloads

### ISSUE THREAD

**Issue by Fretag** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#121] opened 2024-07-27 18:04 UTC
Anyone else having the same problems? I'm not even sure if my version of Civitai Helper is this one? Or if I should be posting this at the Forge creators page. 
![Screenshot 2024-07-27 at 11-02-56 Stable Diffusion](https://github.com/user-attachments/assets/4726ca55-e2bd-4c62-a84b-f5d70850fa70)
![Screenshot 2024-07-27 at 11-01-24 Stable Diffusion](https://github.com/user-attachments/assets/caa43106-1a8b-4230-b223-4eeba62d71b3)

CHv1.8.10: Run get_model_id_from_url
CHv1.8.10: Getting model info for: 578500
CHv1.8.10: Request model info from civitai: 578500
CHv1.8.10: Get subfolder for: F:\SD Forge Manual\models\Stable-diffusion
Traceback (most recent call last):
  File "F:\SD Forge Manual\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "F:\SD Forge Manual\venv\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\SD Forge Manual\venv\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "F:\SD Forge Manual\venv\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "F:\SD Forge Manual\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\SD Forge Manual\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\SD Forge Manual\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\SD Forge Manual\venv\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "F:\SD Forge Manual\extensions\Stable-Diffusion-Webui-Civitai-Helper\ch_lib\sections.py", line 263, in get_model_info_by_url
    files_row.update(
AttributeError: 'Column' object has no attribute 'update'

**Comment by Fretag** [comment] 2024-07-27 18:05
Or it could be something Civitai broke?

**Comment by Fretag** [comment] 2024-07-28 04:59
Seems like the "batch models downloader" works and the "check new models" portion works, 

but not the "download single model" or "get model info"

**Comment by Fretag** [comment] 2024-07-28 16:35
I tried deleting and letting venv rebuild. No luck. Closing this without a solution.

**Comment by zixaphir** [comment] 2024-07-29 21:22
I'm looking into this. The issue currently appears to be a change in Gradio, which I'm trying to track down. For the time being, I'd like this issue to stay open so I can follow it.

**Comment by xSemi** [comment] 2024-08-08 21:22
anytime timeline when it should work again?

**Comment by zixaphir** [comment] 2024-08-11 03:56
I have not yet been able to track down the source of this issue.

**Comment by webik150** [comment] 2024-08-12 19:29
The issue is this: https://github.com/gradio-app/gradio/issues/6339

specifically:

> * Removes the deprecated .update() method from component classes. Instead, you can now just return an instance of a component from your function. I.e. return gr.Textbox(lines=4) instead of gr.Textbox.update(lines=4)

**Comment by zixaphir** [comment] 2024-08-16 04:25
This should be fixed in 1.8.11.

**Closed by zixaphir** 2024-08-16 04:25 UTC

**Comment by Fretag** [comment] 2024-08-16 04:49
Yay! Thank you.
