### ISSUE TITLE
bug Cant download models or get info

### ISSUE THREAD

**Issue by SELEKCJONER** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#91] opened 2024-03-27 22:44 UTC
## Have you read document?
yes
## Have you checked console log window's msg?
yes
## Describe Issue
i use a1111 webui 1.4 and get model doesnt work no matter what always fails with 404: Not Found

## Screenshot for UI issue
![image](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/assets/136343482/55c1b18e-3158-46ab-8e10-453ac5d00196)

## Console log's msg or screenshot for function issue

Civitai Helper: Getting model info by: https://civitai.com/models/150110/felix-argyle
Civitai Helper: Run get_model_id_from_url
Civitai Helper: Request model info from civitai: 150110
Civitai Helper: GET Request failed with error code:
404: Not Found
Civitai Helper: An error occurred while attempting to process model info:
'NoneType' object is not subscriptable
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
output = await app.get_blocks().process_api(
File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gradio/blocks.py", line 1326, in process_api
data = self.postprocess_data(fn_index, result["prediction"], state)
File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gradio/blocks.py", line 1229, in postprocess_data
self.validate_outputs(fn_index, predictions) # type: ignore
File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gradio/blocks.py", line 1204, in validate_outputs
raise ValueError(
ValueError: An event handler (get_model_info_by_url) didn't receive enough output values (needed: 6, received: 1).
Wanted outputs:
[state, textbox, textbox, dropdown, dropdown, <gradio.layouts.Column object at 0x7dbd1f5538e0>]
Received outputs:
[None]

**Comment by zixaphir** [comment] 2024-03-27 22:46
Duplicate of https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/issues/90

**Closed by zixaphir** 2024-03-27 22:46 UTC
